# Generated by Django 6.1.1 on 2026-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(default='Abuja, Nigeria', max_length=150)),
                ('employment_type', models.CharField(default='Full-time', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Position',
                'verbose_name_plural': 'Career Positions',
                'ordering': ['-created_at'],
            },
        ),
    ]
