# Generated by Django 6.1.1 on 2026-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('investment_plan', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('next_of_kin', models.CharField(max_length=150)),
                ('next_of_kin_phone', models.CharField(max_length=30)),
                ('next_of_kin_address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Investment Application',
                'verbose_name_plural': 'Investment Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
