# Generated by Django 6.1.1 on 2026-09-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_alter_propertyimage_image_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_plan', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Instalment')], default='full', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('part_paid', 'Part Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='properties.property')),
            ],
            options={
                'verbose_name': 'Client Record',
                'verbose_name_plural': 'Client Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pos', 'POS'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Payment',
                'verbose_name_plural': 'Client Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
