# Generated by Django 6.1.1 on 2026-09-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertyvideo',
            options={'verbose_name': 'Property Video', 'verbose_name_plural': 'Property Videos'},
        ),
    ]
