# Generated by Django 6.1.1 on 2026-09-08 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to='properties/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'], message='Please upload a valid video file (MP4, WebM, or MOV).')]),
        ),
    ]
