# Generated by Django 6.1.1 on 2026-09-08 23:38

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'], message='Please upload a valid video file (MP4, WebM, or MOV).')], verbose_name='video'),
        ),
    ]
