# Generated by Django 6.1.1 on 2026-09-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
    ]
