# Generated by Django 6.1.1 on 2026-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('office_type', models.CharField(choices=[('head', 'Head Office'), ('branch', 'Branch Office')], default='branch', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Abuja', max_length=100)),
                ('state', models.CharField(default='FCT', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['office_type', 'name'],
            },
        ),
    ]
